# Generated by Django 3.1.5 on 2021-04-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tremendo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
