# Generated by Django 3.1.5 on 2021-05-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tremendo', '0005_auto_20210430_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='tremendo.profile'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
