# Generated by Django 3.1.5 on 2021-05-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tremendo', '0006_auto_20210501_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_verified',
        ),
    ]
